### ISSUE TITLE
conversion of eor 21cm fast binary file to fits file showing error

### ISSUE THREAD

**Issue by Arnab-half-blood-prince** [liweitianux/cdae-eor#1]
Hi,
I have been trying to simulate a visibility set with just EoR signal as sky-model. 
I tried to use 21cmfast_lightcone.py to convert the binary file to fits file.
But the shape is mismatching. 
I have downloaded the binary file from https://drive.google.com/drive/folders/1XqRNdyDGFChzWNEqWrC7OZPL9mR4G9n2 
The binary file is of size 18886656 and not in 1024**3

Do you think the binary file I have downloaded is wrong?

**Comment by liweitianux** [comment]
Hi, it seems your downloaded file is incomplete.  The data file should be 4GB, so please retry the download to make sure the download is complete ;)

The modification time of the dataset is 2018 Dec; I think the Authors may have updated the dataset after we've used it.  But I believe the format of the dataset is the same and my Python script should work.

My colleague is downloading the data file to test the Python script.  We'll get the result to you soon.

Regards.

**Comment by Arnab-half-blood-prince** [comment]
It maybe the case. But, I think they changed the simulated files. 

I used 21cmFAST version3, the recently released python version, and simulated a lightcone between z=7 to z =11.
And then follow your prescription. It worked. Also, for the lightcone cube, the dimension is different along the z-direction. I gave input for a  cube of size 256 grids along each direction for a 1000 MPc scale simulation. The resultant brightness_temp cube is of size [256,256,265].
 
I guess this is mainly due to lighcone simulation or lightray evolution. 
So, when I passed this cube in your 21cmFAST_lighcone.py with the known dimension [256,256,265], it worked.

**Comment by liweitianux** [comment]
OK. My colleague has tested the data file and the Python script. The newly downloaded data file is the same as my download years ago and the Python script still works as expected. See the following screenshot:

![457987670](https://user-images.githubusercontent.com/686169/99868071-3a9b3280-2bfa-11eb-8445-a07cbac976db.jpg)

Besides, the MD5 checksum of the data file `delta_T_v3_no_halos__zstart005.00000_zend009.56801_FLIPBOXES0_1024_1600Mpc_lighttravel`
is `d1b7d6c854bff9558c45286895be7f7f`.  So you can further check it.

Regards

**Comment by Arnab-half-blood-prince** [comment]
Hi, it worked for me. Thanks for the help.

Just need one suggestion- Is it possible to simulate a visibility cube in Oskar, by providing an EoR sky cube as a sky model. 
Instead of simulating ms files for each lightcone slice and then image it in wsclean, I am thinking if it is possible to combine all the slices of sky signal in a single fits cube and simulating an ms set with similar frequency channels.  

Any suggestions?

**Comment by liweitianux** [comment]
Hi, glad it worked for you :)

No, OSKAR cannot accept a sky cube, and you need to feed it slice by slice.  So I've written another script to help with this:

https://github.com/liweitianux/atoolbox/blob/master/astro/oskar/run_oskar.py

Hope this script helps you.

**Comment by Arnab-half-blood-prince** [comment]
Yes, I know this script. And entire simulation with your tools is done. 
I was just curious whether it can be done with a one signal cube using oskar. I checked github page of oskar too. But not much help.
Thanks for the suggestions and help.
I am closing this.
